<?php

/**
 * This is the model base class for the table "user_oauth".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giiy.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserOauth".
 *
 * Columns in table "user_oauth" available as properties of the model,
 * followed by relations of table "user_oauth" available as properties of the model.
 *
 * @property integer $user_id
 * @property integer $id
 * @property string $service
 * @property string $foreign_id
 *
 * @property User $user
 *
 */
abstract class BaseUserOauth extends CActiveRecord {

    public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_oauth';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserOauth|UserOauths', $n);
	}

	public function rules() {
		return array(
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('service', 'length', 'max'=>255),
			array('foreign_id', 'length', 'max'=>1023),
			array('user_id, service, foreign_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, id, service, foreign_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'id' => Yii::t('app', 'ID'),
			'service' => Yii::t('app', 'Service'),
			'foreign_id' => Yii::t('app', 'Foreign'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('t.user_id', $this->getAttribute('user_id'));
		$criteria->compare('t.id', $this->getAttribute('id'));
		$criteria->compare('t.service', $this->getAttribute('service'), true);
		$criteria->compare('t.foreign_id', $this->getAttribute('foreign_id'), true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}